
- name: "make folder"
- name: "copy"
- name: "unzip"
- name: "make sure we are cd into the directory we just made"
- name: "build"

- name: "install npm and start"
  become: yes
    npm install
    pm2 stop default
    pm2 start npm -- start