




# unzip
- name: "Extract ./artifact.tar.gz into ./backend"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: start app
  become: yes
  shell: |
    cd ~/backend
    npm install 
    pm2 stop default 
    pm2 start npm -- start

# - name: "make sure we are cd into the directory we just made"
# - name: "build"

# - name: "install npm and start"
#   become: yes
#   shell: |
#     cd ./backend
#     npm install
#     npm run build
#     pm2 stop default
#     pm2 start npm -- start
#     cd dist
#     pm2 start main.js